# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rag.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'rag.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\trag.proto\x12\x03rag\"/\n\x0fRetrieveRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\r\n\x05top_k\x18\x02 \x01(\x05\"%\n\x05\x43hunk\x12\x0e\n\x06source\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\".\n\x10RetrieveResponse\x12\x1a\n\x06\x63hunks\x18\x01 \x03(\x0b\x32\n.rag.Chunk\"?\n\x0fGenerateRequest\x12\x10\n\x08question\x18\x01 \x01(\t\x12\x1a\n\x06\x63hunks\x18\x02 \x03(\x0b\x32\n.rag.Chunk\"\"\n\x10GenerateResponse\x12\x0e\n\x06\x61nswer\x18\x01 \x01(\t2K\n\x10RetrievalService\x12\x37\n\x08Retrieve\x12\x14.rag.RetrieveRequest\x1a\x15.rag.RetrieveResponse2L\n\x11GenerationService\x12\x37\n\x08Generate\x12\x14.rag.GenerateRequest\x1a\x15.rag.GenerateResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rag_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RETRIEVEREQUEST']._serialized_start=18
  _globals['_RETRIEVEREQUEST']._serialized_end=65
  _globals['_CHUNK']._serialized_start=67
  _globals['_CHUNK']._serialized_end=104
  _globals['_RETRIEVERESPONSE']._serialized_start=106
  _globals['_RETRIEVERESPONSE']._serialized_end=152
  _globals['_GENERATEREQUEST']._serialized_start=154
  _globals['_GENERATEREQUEST']._serialized_end=217
  _globals['_GENERATERESPONSE']._serialized_start=219
  _globals['_GENERATERESPONSE']._serialized_end=253
  _globals['_RETRIEVALSERVICE']._serialized_start=255
  _globals['_RETRIEVALSERVICE']._serialized_end=330
  _globals['_GENERATIONSERVICE']._serialized_start=332
  _globals['_GENERATIONSERVICE']._serialized_end=408
# @@protoc_insertion_point(module_scope)
